name: JavaPlugin
version: '${project.version}'
main: dev.mrdragon.javaplugin.Plugin
api-version: '1.16'

commands:
  dslink:
    description: Vincule a sua conta do minecraft com o discord.
    usage: /dslink
  dsunlink:
    description: Desvincule a sua conta do minecraft com o discord.
    usage: /dsunlink
  test:
    description: Comando teste.
    usage: /test